import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { fontSans, fontDisplay } from "@/lib/fonts";
import { Nav } from "@/components/shared/nav";
import { Providers } from "@/components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased dark overflow-x-hidden",
            fontSans.variable,
            fontDisplay.variable
          )}
        >
          <Nav />
          <main className="">{children}</main>
        </body>
      </html>
    </Providers>
  );
}
